XLOADER_DIR := $(ANDROID_BUILD_TOP)/bootable/bootloader/x-loader
XLOADER_IMAGE_FILE_NAME := x-loader.bin.ift
XLOADER_INTERNAL_IMAGE := $(XLOADER_DIR)/MLO
XLOADER_OUTPUT_IMAGE := $(PRODUCT_OUT)/$(XLOADER_IMAGE_FILE_NAME)

XLOADER_CONFIG_OUT := $(XLOADER_DIR)/include/config.mk
XLOADER_CROSS_COMPILE := arm-none-linux-gnueabi-

ifeq ($(TARGET_MACH),OMAP4-HS)
CHIP_VER := "CHIP_VER=HS"
else
ifeq ($(TARGET_MACH),OMAP4-EMU22)
CHIP_VER := "CHIP_VER=ES2.2"
else
ifeq ($(TARGET_MACH),OMAP4-EMU20)
CHIP_VER := "CHIP_VER=ES2.0"
else
ifeq ($(TARGET_MACH),OMAP4-GP)
CHIP_VER := "CHIP_VER=GP"
else
echo "Error : Not defined = CHIP_VER"
endif
endif
endif
endif

ifeq ($(TARGET_PRODUCT),cx2)
CHIP_VER := "CHIP_VER=HS"
endif

.PHONY: xloader
xloader: $(XLOADER_OUTPUT_IMAGE)

$(XLOADER_OUTPUT_IMAGE): $(XLOADER_INTERNAL_IMAGE)
	cat $(XLOADER_DIR)/reference/head.hex $< > $@

.PHONY: $(XLOADER_INTERNAL_IMAGE)
$(XLOADER_INTERNAL_IMAGE): $(XLOADER_CONFIG_OUT) 
	+$(MAKE) -C $(XLOADER_DIR) ift CROSS_COMPILE=$(XLOADER_CROSS_COMPILE) $(CHIP_VER)

.PHONY: $(XLOADER_CONFIG_OUT)
$(XLOADER_CONFIG_OUT):
	$(MAKE) -C $(XLOADER_DIR) $(XLOADER_CONFIG) CROSS_COMPILE=$(XLOADER_CROSS_COMPILE)

cxloader:
	$(MAKE) -C $(XLOADER_DIR) distclean
	-rm -f $(XLOADER_OUTPUT_IMAGE)
